# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-01-29 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_author',
            field=models.CharField(default='Kyrie Irving', max_length=1000),
        ),
    ]
