# Generated by Django 2.0.1 on 2018-01-30 18:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20180129_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='asd', max_length=1000)),
                ('story_url', models.URLField(default='https://www.google.ca/')),
                ('timestamp', models.TimeField(default=datetime.time(18, 13, 19, 367252))),
            ],
        ),
        migrations.CreateModel(
            name='FeedUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='feeddetail',
            name='feed_url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.FeedUrl'),
        ),
    ]
