# Generated by Django 2.0.1 on 2018-02-06 15:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20180205_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeddetail',
            name='timestamp',
            field=models.TimeField(default=datetime.time(15, 39, 41, 524960)),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='day',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='time',
            field=models.TimeField(default=datetime.time(15, 39, 41, 526806)),
        ),
    ]
