# Generated by Django 2.0.1 on 2018-02-06 21:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20180206_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeddetail',
            name='timestamp',
            field=models.TimeField(default=datetime.time(21, 38, 13, 865833)),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Day'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='time',
            field=models.TimeField(default=datetime.time(21, 38, 13, 867772)),
        ),
    ]
