# Generated by Django 2.0.1 on 2018-02-06 21:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20180206_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeddetail',
            name='timestamp',
            field=models.TimeField(default=datetime.time(21, 43, 37, 416199)),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='day',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='time',
            field=models.TimeField(default=datetime.time(21, 43, 37, 418362)),
        ),
    ]
